/** Canonical Uzbekistan geo catalog — Country → Province → City (stable slugs). */

export type ProvinceTypeSeed = 'REGION' | 'CITY' | 'REPUBLIC';

export type GeoCitySeed = { name: string; slug: string };
export type GeoProvinceSeed = {
  name: string;
  slug: string;
  type: ProvinceTypeSeed;
  cities: GeoCitySeed[];
};

export const UZBEKISTAN_COUNTRY = {
  name: 'Uzbekistan',
  slug: 'uzbekistan',
  iso2: 'UZ',
  iso3: 'UZB',
  phoneCode: '+998',
  currencyCode: 'UZS',
} as const;

/** Legacy City.region / slug → province slug (existing 15 rows). */
export const LEGACY_CITY_PROVINCE: Record<string, string> = {
  tashkent: 'tashkent-city',
  chirchiq: 'tashkent-region',
  angren: 'tashkent-region',
  nukus: 'karakalpakstan',
  samarkand: 'samarkand',
  bukhara: 'bukhara',
  andijan: 'andijan',
  namangan: 'namangan',
  fergana: 'fergana',
  urgench: 'khorezm',
  navoi: 'navoi',
  karshi: 'kashkadarya',
  termez: 'surkhandarya',
  jizzakh: 'jizzakh',
  gulistan: 'sirdarya',
};

export const LEGACY_REGION_PROVINCE: Record<string, string> = {
  tashkent: 'tashkent-city',
  'tashkent region': 'tashkent-region',
  karakalpakstan: 'karakalpakstan',
  samarkand: 'samarkand',
  bukhara: 'bukhara',
  andijan: 'andijan',
  namangan: 'namangan',
  fergana: 'fergana',
  khorezm: 'khorezm',
  navoi: 'navoi',
  kashkadarya: 'kashkadarya',
  surkhandarya: 'surkhandarya',
  jizzakh: 'jizzakh',
  sirdarya: 'sirdarya',
};

export const UZBEKISTAN_PROVINCES: GeoProvinceSeed[] = [
  {
    name: 'Tashkent City',
    slug: 'tashkent-city',
    type: 'CITY',
    cities: [
      { name: 'Tashkent', slug: 'tashkent' },
      { name: 'Bektemir', slug: 'bektemir' },
      { name: 'Yashnobod', slug: 'yashnobod' },
      { name: 'Sergeli', slug: 'sergeli' },
      { name: 'Uchtepa', slug: 'uchtepa' },
      { name: 'Chilanzar', slug: 'chilanzar' },
      { name: 'Yunusabad', slug: 'yunusabad' },
      { name: 'Mirzo Ulugbek', slug: 'mirzo-ulugbek' },
      { name: 'Shaykhontohur', slug: 'shaykhontohur' },
      { name: 'Olmazor', slug: 'olmazor' },
      { name: 'Yakkasaray', slug: 'yakkasaray' },
      { name: 'Mirobod', slug: 'mirobod' },
    ],
  },
  {
    name: 'Tashkent Region',
    slug: 'tashkent-region',
    type: 'REGION',
    cities: [
      { name: 'Nurafshon', slug: 'nurafshon' },
      { name: 'Chirchiq', slug: 'chirchiq' },
      { name: 'Angren', slug: 'angren' },
      { name: 'Almalyk', slug: 'almalyk' },
      { name: 'Bekabad', slug: 'bekabad' },
      { name: 'Yangiyul', slug: 'yangiyul' },
      { name: 'Gazalkent', slug: 'gazalkent' },
      { name: 'Keles', slug: 'keles' },
      { name: 'Parkent', slug: 'parkent' },
      { name: 'Pskent', slug: 'pskent' },
      { name: 'Chinaz', slug: 'chinaz' },
      { name: 'Ohangaron', slug: 'ohangaron' },
      { name: 'Zangiota', slug: 'zangiota' },
      { name: 'Toytepa', slug: 'toytepa' },
    ],
  },
  {
    name: 'Republic of Karakalpakstan',
    slug: 'karakalpakstan',
    type: 'REPUBLIC',
    cities: [
      { name: 'Nukus', slug: 'nukus' },
      { name: 'Kungrad', slug: 'kungrad' },
      { name: 'Chimbay', slug: 'chimbay' },
      { name: 'Beruniy', slug: 'beruniy' },
      { name: 'Takhiatash', slug: 'takhiatash' },
      { name: 'Muynak', slug: 'muynak' },
      { name: 'Khujayli', slug: 'khujayli' },
      { name: 'Turtkul', slug: 'turtkul' },
      { name: 'Mangit', slug: 'mangit' },
      { name: 'Kegeyli', slug: 'kegeyli' },
    ],
  },
  {
    name: 'Andijan',
    slug: 'andijan',
    type: 'REGION',
    cities: [
      { name: 'Andijan', slug: 'andijan' },
      { name: 'Asaka', slug: 'asaka' },
      { name: 'Khanabad', slug: 'khanabad' },
      { name: 'Shahrikhan', slug: 'shahrikhan' },
      { name: 'Karasu', slug: 'karasu-andijan' },
      { name: 'Poytug', slug: 'poytug' },
      { name: 'Pakhtaabad', slug: 'pakhtaabad' },
      { name: 'Marhamat', slug: 'marhamat' },
      { name: 'Baliqchi', slug: 'baliqchi' },
      { name: 'Jalakuduk', slug: 'jalakuduk' },
    ],
  },
  {
    name: 'Bukhara',
    slug: 'bukhara',
    type: 'REGION',
    cities: [
      { name: 'Bukhara', slug: 'bukhara' },
      { name: 'Kagan', slug: 'kagan' },
      { name: 'Gijduvan', slug: 'gijduvan' },
      { name: 'Romitan', slug: 'romitan' },
      { name: 'Vabkent', slug: 'vabkent' },
      { name: 'Shofirkon', slug: 'shofirkon' },
      { name: 'Peshku', slug: 'peshku' },
      { name: 'Jondor', slug: 'jondor' },
      { name: 'Karaulbazar', slug: 'karaulbazar' },
      { name: 'Alat', slug: 'alat' },
    ],
  },
  {
    name: 'Fergana',
    slug: 'fergana',
    type: 'REGION',
    cities: [
      { name: 'Fergana', slug: 'fergana' },
      { name: 'Margilan', slug: 'margilan' },
      { name: 'Kokand', slug: 'kokand' },
      { name: 'Quvasoy', slug: 'quvasoy' },
      { name: 'Rishton', slug: 'rishton' },
      { name: 'Oltiariq', slug: 'oltiariq' },
      { name: 'Toshloq', slug: 'toshloq' },
      { name: 'Yaypan', slug: 'yaypan' },
      { name: 'Beshariq', slug: 'beshariq' },
      { name: 'Dangara', slug: 'dangara' },
      { name: 'Uchkoprik', slug: 'uchkoprik' },
    ],
  },
  {
    name: 'Jizzakh',
    slug: 'jizzakh',
    type: 'REGION',
    cities: [
      { name: 'Jizzakh', slug: 'jizzakh' },
      { name: 'Gallaorol', slug: 'gallaorol' },
      { name: 'Dustlik', slug: 'dustlik' },
      { name: 'Zarbdor', slug: 'zarbdor' },
      { name: 'Forish', slug: 'forish' },
      { name: 'Pakhtakor', slug: 'pakhtakor' },
      { name: 'Zafarobod', slug: 'zafarobod' },
      { name: 'Yangjobod', slug: 'yangjobod' },
    ],
  },
  {
    name: 'Kashkadarya',
    slug: 'kashkadarya',
    type: 'REGION',
    cities: [
      { name: 'Karshi', slug: 'karshi' },
      { name: 'Shahrisabz', slug: 'shahrisabz' },
      { name: 'Kitab', slug: 'kitab' },
      { name: 'Yakkabog', slug: 'yakkabog' },
      { name: 'Kamashi', slug: 'kamashi' },
      { name: 'Kasbi', slug: 'kasbi' },
      { name: 'Muborak', slug: 'muborak' },
      { name: 'Nishon', slug: 'nishon' },
      { name: 'Guzar', slug: 'guzar' },
      { name: 'Dehkanabad', slug: 'dehkanabad' },
      { name: 'Chirakchi', slug: 'chirakchi' },
    ],
  },
  {
    name: 'Khorezm',
    slug: 'khorezm',
    type: 'REGION',
    cities: [
      { name: 'Urgench', slug: 'urgench' },
      { name: 'Khiva', slug: 'khiva' },
      { name: 'Pitnak', slug: 'pitnak' },
      { name: 'Gurlan', slug: 'gurlan' },
      { name: 'Shovot', slug: 'shovot' },
      { name: 'Yangiarik', slug: 'yangiarik' },
      { name: 'Bagat', slug: 'bagat' },
      { name: 'Hazorasp', slug: 'hazorasp' },
      { name: 'Koshkopir', slug: 'koshkopir' },
    ],
  },
  {
    name: 'Namangan',
    slug: 'namangan',
    type: 'REGION',
    cities: [
      { name: 'Namangan', slug: 'namangan' },
      { name: 'Chust', slug: 'chust' },
      { name: 'Pop', slug: 'pop' },
      { name: 'Uychi', slug: 'uychi' },
      { name: 'Kasansay', slug: 'kasansay' },
      { name: 'Turakurgan', slug: 'turakurgan' },
      { name: 'Chortoq', slug: 'chortoq' },
      { name: 'Mingbulak', slug: 'mingbulak' },
      { name: 'Yangikurgan', slug: 'yangikurgan' },
      { name: 'Uchkurgan', slug: 'uchkurgan' },
    ],
  },
  {
    name: 'Navoi',
    slug: 'navoi',
    type: 'REGION',
    cities: [
      { name: 'Navoi', slug: 'navoi' },
      { name: 'Zarafshan', slug: 'zarafshan' },
      { name: 'Uchkuduk', slug: 'uchkuduk' },
      { name: 'Kyzyltepa', slug: 'kyzyltepa' },
      { name: 'Karmana', slug: 'karmana' },
      { name: 'Nurata', slug: 'nurata' },
      { name: 'Tomdi', slug: 'tomdi' },
      { name: 'Konimex', slug: 'konimex' },
    ],
  },
  {
    name: 'Samarkand',
    slug: 'samarkand',
    type: 'REGION',
    cities: [
      { name: 'Samarkand', slug: 'samarkand' },
      { name: 'Kattakurgan', slug: 'kattakurgan' },
      { name: 'Urgut', slug: 'urgut' },
      { name: 'Juma', slug: 'juma' },
      { name: 'Aktash', slug: 'aktash' },
      { name: 'Bulungur', slug: 'bulungur' },
      { name: 'Ishtikhan', slug: 'ishtikhan' },
      { name: 'Nurobod', slug: 'nurobod' },
      { name: 'Pastdargom', slug: 'pastdargom' },
      { name: 'Payarik', slug: 'payarik' },
      { name: 'Taylak', slug: 'taylak' },
    ],
  },
  {
    name: 'Sirdarya',
    slug: 'sirdarya',
    type: 'REGION',
    cities: [
      { name: 'Gulistan', slug: 'gulistan' },
      { name: 'Yangiyer', slug: 'yangiyer' },
      { name: 'Shirin', slug: 'shirin' },
      { name: 'Baht', slug: 'baht' },
      { name: 'Sardoba', slug: 'sardoba' },
      { name: 'Boyovut', slug: 'boyovut' },
      { name: 'Khavast', slug: 'khavast' },
      { name: 'Mirzaabad', slug: 'mirzaabad' },
    ],
  },
  {
    name: 'Surkhandarya',
    slug: 'surkhandarya',
    type: 'REGION',
    cities: [
      { name: 'Termez', slug: 'termez' },
      { name: 'Denov', slug: 'denov' },
      { name: 'Shargun', slug: 'shargun' },
      { name: 'Boysun', slug: 'boysun' },
      { name: 'Jarqorgon', slug: 'jarqorgon' },
      { name: 'Kumkurgan', slug: 'kumkurgan' },
      { name: 'Sariosiyo', slug: 'sariosiyo' },
      { name: 'Uzun', slug: 'uzun' },
      { name: 'Muzrabot', slug: 'muzrabot' },
      { name: 'Sherobod', slug: 'sherobod' },
    ],
  },
  {
    name: 'Other Uzbekistan',
    slug: 'other-uzbekistan',
    type: 'REGION',
    cities: [],
  },
];

export function allUzbekistanCitySlugs(): string[] {
  return UZBEKISTAN_PROVINCES.flatMap((p) => p.cities.map((c) => c.slug));
}
